env:
  WITH_COVERAGE: true
jobs:
  author:
    name: author
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout project
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Run tests
      run: ./dev-support/checks/author.sh
    - continue-on-error: true
      if: always()
      name: Upload results
      uses: actions/upload-artifact@v4
      with:
        name: author
        path: target/author
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout project
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Cache for maven dependencies
      uses: actions/cache@v4
      with:
        key: maven-repo-${{ hashFiles('**/pom.xml') }}
        path: '~/.m2/repository

          !~/.m2/repository/org/apache/ratis

          '
        restore-keys: 'maven-repo-

          '
    - continue-on-error: true
      name: Setup java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 8
    - continue-on-error: true
      name: Run a full build
      run: ./dev-support/checks/build.sh -Prelease assembly:single
    - continue-on-error: true
      name: Store binaries for tests
      uses: actions/upload-artifact@v4
      with:
        name: ratis-bin
        path: 'ratis-assembly/target/apache-ratis-*.tar.gz

          !ratis-assembly/target/apache-ratis-*-src.tar.gz

          '
        retention-days: 1
    - continue-on-error: true
      name: Store source tarball for compilation
      uses: actions/upload-artifact@v4
      with:
        name: ratis-src
        path: ratis-assembly/target/apache-ratis-*-src.tar.gz
        retention-days: 1
  checkstyle:
    name: checkstyle
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout project
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Cache for maven dependencies
      uses: actions/cache/restore@v4
      with:
        key: maven-repo-${{ hashFiles('**/pom.xml') }}
        path: '~/.m2/repository

          !~/.m2/repository/org/apache/ratis

          '
        restore-keys: 'maven-repo-

          '
    - continue-on-error: true
      name: Run tests
      run: ./dev-support/checks/checkstyle.sh
    - continue-on-error: true
      if: always()
      name: Upload results
      uses: actions/upload-artifact@v4
      with:
        name: checkstyle
        path: target/checkstyle
  compile:
    needs:
    - build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Download source tarball
      uses: actions/download-artifact@v4
      with:
        name: ratis-src
    - continue-on-error: true
      name: Untar sources
      run: 'tar --strip-components 1 -xzvf apache-ratis-*-src.tar.gz

        '
    - continue-on-error: true
      name: Cache for maven dependencies
      uses: actions/cache/restore@v4
      with:
        key: maven-repo-${{ hashFiles('**/pom.xml') }}
        path: '~/.m2/repository

          !~/.m2/repository/org/apache/ratis

          '
        restore-keys: 'maven-repo-

          '
    - continue-on-error: true
      name: Setup java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: Run a full build
      run: ./dev-support/checks/build.sh
    strategy:
      fail-fast: false
      matrix:
        java:
        - 11
  coverage:
    if: (github.repository == 'apache/ratis' || github.repository == 'apache/incubator-ratis')
      && github.event_name != 'pull_request'
    needs:
    - build
    - unit
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout project
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: Cache for maven dependencies
      uses: actions/cache/restore@v4
      with:
        key: maven-repo-${{ hashFiles('**/pom.xml') }}
        path: '~/.m2/repository

          !~/.m2/repository/org/apache/ratis

          '
        restore-keys: 'maven-repo-

          '
    - continue-on-error: true
      name: Setup java 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        path: target/artifacts
    - continue-on-error: true
      name: Untar binaries
      run: 'mkdir -p ratis-assembly/target

        tar xzvf target/artifacts/ratis-bin/apache-ratis*.tar.gz -C ratis-assembly/target

        '
    - continue-on-error: true
      name: Calculate combined coverage
      run: ./dev-support/checks/coverage.sh
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
      name: Upload coverage to Sonar
      run: ./dev-support/checks/sonar.sh
    - continue-on-error: true
      if: always()
      name: Archive build results
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.job }}
        path: target/${{ github.job }}
  findbugs:
    name: findbugs
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Setup java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 8
    - continue-on-error: true
      name: Checkout project
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Cache for maven dependencies
      uses: actions/cache/restore@v4
      with:
        key: maven-repo-${{ hashFiles('**/pom.xml') }}
        path: '~/.m2/repository

          !~/.m2/repository/org/apache/ratis

          '
        restore-keys: 'maven-repo-

          '
    - continue-on-error: true
      name: Run tests
      run: ./dev-support/checks/findbugs.sh
    - continue-on-error: true
      if: always()
      name: Upload results
      uses: actions/upload-artifact@v4
      with:
        name: findbugs
        path: target/findbugs
  rat:
    name: rat
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout project
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Cache for maven dependencies
      uses: actions/cache/restore@v4
      with:
        key: maven-repo-${{ hashFiles('**/pom.xml') }}
        path: '~/.m2/repository

          !~/.m2/repository/org/apache/ratis

          '
        restore-keys: 'maven-repo-

          '
    - continue-on-error: true
      name: Run tests
      run: ./dev-support/checks/rat.sh
    - continue-on-error: true
      if: always()
      name: Upload results
      uses: actions/upload-artifact@v4
      with:
        name: rat
        path: target/rat
  unit:
    name: unit
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Add the current IP address, long hostname and short hostname record to
        /etc/hosts file
      run: 'echo -e "$(ip addr show eth0 | grep "inet\b" | awk ''{print $2}'' | cut
        -d/ -f1)\t$(hostname -f) $(hostname -s)" | sudo tee -a /etc/hosts

        '
    - continue-on-error: true
      name: Checkout project
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Cache for maven dependencies
      uses: actions/cache/restore@v4
      with:
        key: maven-repo-${{ hashFiles('**/pom.xml') }}
        path: '~/.m2/repository

          !~/.m2/repository/org/apache/ratis

          '
        restore-keys: 'maven-repo-

          '
    - continue-on-error: true
      name: Setup java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 8
    - continue-on-error: true
      name: Run tests
      run: ./dev-support/checks/unit.sh -P${{ matrix.profile }}-tests
    - continue-on-error: true
      if: ${{ !cancelled() }}
      name: Summary of failures
      run: cat target/${{ github.job }}/summary.txt
    - continue-on-error: true
      if: ${{ !cancelled() }}
      name: Upload results
      uses: actions/upload-artifact@v4
      with:
        name: unit-${{ matrix.profile }}
        path: target/unit
    strategy:
      fail-fast: false
      matrix:
        profile:
        - grpc
        - server
        - misc
name: build-branch
on:
  repository_dispatch:
    types: trigger-ga___post-commit.yml
