env:
  FAIL_FAST: ${{ github.event.inputs.fail-fast }}
  ITERATIONS: ${{ github.event.inputs.iterations }}
  MAVEN_OPTS: -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.http.retryHandler.class=standard
    -Dmaven.wagon.http.retryHandler.count=3
  TEST_CLASS: ${{ github.event.inputs.test-class }}
  TEST_METHOD: ${{ github.event.inputs.test-method }}
jobs:
  count-failures:
    if: ${{ always() }}
    needs: test
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Download build results
      uses: actions/download-artifact@v4
    - continue-on-error: true
      name: Count failures
      run: "failures=$(find . -name 'summary.txt' | grep -v 'iteration' | xargs grep\
        \ -v 'exit code: 0' | wc -l)\necho \"Total failures: $failures\"\nif [[ $failures\
        \ -gt 0 ]]; then\n  echo \"\"\n  echo \"Failed runs:\"\n  grep 'exit code:\
        \ 1' */summary.txt | grep -o 'split.*teration [0-9]*' | sed -e 's/.summary.txt:/\
        \ /' -e 's/-/ /' | sort -g -k2 -k4\n  echo \"\"\n  exit 1\nfi\n"
  prepare:
    outputs:
      matrix: ${{ steps.generate.outputs.matrix }}
      test-spec: ${{ steps.test-spec.outputs.test-spec }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      id: generate
      name: Generate test matrix
      run: "splits=()\nfor ((i = 1; i <= ${{ github.event.inputs.splits }}; i++));\
        \ do\n    splits+=(\"$i\")\ndone\nprintf -v x \"%s,\" \"${splits[@]}\"\nsplit_matrix=\"\
        [${x%,}]\"\necho \"matrix=$split_matrix\" >> $GITHUB_OUTPUT\n"
    - continue-on-error: true
      id: test-spec
      name: Define test spec
      run: "if [[ -z \"$TEST_METHOD\" ]]; then\n  test_spec=\"$TEST_CLASS\"\nelse\n\
        \  test_spec=\"$TEST_CLASS#$TEST_METHOD\"\nfi\necho \"Test to be run: $test_spec\"\
        \necho \"test-spec=$test_spec\" >> $GITHUB_OUTPUT\n"
  test:
    env:
      TEST_SPEC: ${{ needs.prepare.outputs.test-spec }}
    if: ${{ always() }}
    needs:
    - prepare
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.inputs.ref }}
    - continue-on-error: true
      name: Cache for maven dependencies
      uses: actions/cache@v4
      with:
        key: maven-repo-${{ hashFiles('**/pom.xml') }}
        path: '~/.m2/repository

          !~/.m2/repository/org/apache/ratis

          '
        restore-keys: 'maven-repo-

          '
    - continue-on-error: true
      name: Setup java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 8
    - continue-on-error: true
      name: Validate test spec
      run: if [[ -z "$TEST_SPEC" ]]; then exit 1; fi
    - continue-on-error: true
      name: Execute ${{ env.TEST_SPEC }}
      run: dev-support/checks/unit.sh -Dtest="$TEST_SPEC"
    - continue-on-error: true
      if: ${{ !cancelled() }}
      name: Summary of failures
      run: dev-support/checks/_summary.sh target/unit/summary.txt
    - continue-on-error: true
      if: always()
      name: Archive build results
      uses: actions/upload-artifact@v4
      with:
        name: result-${{ env.TEST_CLASS }}-split-${{ matrix.split }}
        path: target/unit
    strategy:
      fail-fast: ${{ fromJson(github.event.inputs.fail-fast) }}
      matrix:
        split: ${{ fromJson(needs.prepare.outputs.matrix) }}
name: repeat-test
on:
  repository_dispatch:
    types: trigger-ga___repeat-test.yml
run-name: ${{ github.event_name == 'workflow_dispatch' && format('{0}#{1}[{2}]-{3}x{4}',
  inputs.test-class, inputs.test-method, inputs.ref, inputs.splits, inputs.iterations)
  || '' }}
